fix: name limits error on DB role manager container app job name (#39)
## Ticket

Resolves an issue where application names can cause the DB Role Manager
Container App Job to exceed Azure’s 32- character limit resulting in
deployment errors.

## Changes

- In a backward-compatible way, trim Container App Job names so they do
not exceed the Azure 32-character limit, while avoiding changes to
existing App Job names that could cause Terraform to replace current
jobs

## Testing

### Before

400 Bad Request from the ARM API

```
Error: creating/updating Container App Job: ... 
InvalidContainerAppJobName: The name 'xxx' is invalid. 
Container App Job names must be between 1 and 32 characters long,
can only contain lowercase alphanumeric characters and '-', 
must start with a letter and end with an alphanumeric character. 
```        

### After

<img width="1176" height="143" alt="image"
src="https://github.com/user-attachments/assets/f2fe267f-5f41-450c-96c5-109c1e61e24d"
/>